#import 4shared
import bitshare
#import chomikuj
import depositfiles
#import easyshare
#import enterupload
import filefactory
import fileserve
import filesonic
#import freakshare
#import gigasize
import hotfile
import letitbit
import mediafire
import megaporn
import megashares
import megaupload
import megavideo
import netload
import oron
import pornhub
import rapidshare
import redtube
import shareonline
#import soundcloud
import turbobit
import uploaded
#import uploading
import uploadstation
#import usershare
import wupload
import x7
import xhamster
import xvideos
import youjizz
import youporn
import youtube
