import filesonic
import wupload
import fileserve
import rapidshare
import hotfile
import megaupload
import megavideo
import turbobit
import netload
import oron
import depositfiles
import uploadstation
import uploaded
#import freakshare
import bitshare
#import uploading
import x7
#import easyshare
#import enterupload
#import usershare
#import chomikuj
import letitbit
import mediafire
#import 4shared
import megashares
#import gigasize
#import soundcloud
import youtube
import megaporn
import redtube
import xvideos
import xhamster
import pornhub
import youporn
import youjizz
