# -*- coding: utf-8 -*-

__all__ = [
    'fichier',  # 1fichier
    # '4shared',
    'bitshare',
    'catshare',
    'chomikuj',
    'crocko',
    'depfile',
    'depositfiles',
    # 'easyshare',
    # 'enterupload',
    'expressvpn',
    'extabit',
    'fileboom',
    'filefactory',
    'filesmonster',
    'fileshark',
    'freakshare',
    # 'gigasize',
    'hellshare',
    'imgur',
    'interia',
    'keep2share',
    'kickass',
    'letitbit',
    'lunaticfiles',
    'mediafire',
    'megashares',
    'netload',
    'onet',
    'pornhub',
    'rapidshare',
    'rapidgator',
    'rapidu',
    'redtube',
    'rlslog',
    'ryushare',
    'shareonline',
    # 'soundclound',
    'turbobit',
    'uploaded',
    # 'uploading',
    'uploadstation',
    # 'usershare',
    'videobam',
    'wp',
    'xhamster',
    'xvideos',
    'youjizz',
    'youporn',
    'youtube',
]
